localhost_development:
  backend:
    name: file-system
    api_root: /api

backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads
display_url: https://recept.netlify.com

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

collections:
  - name: 'recept'
    label: 'Recept'
    folder: 'src/pages/recept'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'recept',
        }
      - { label: 'URL', name: 'url', widget: 'hidden', default: '' }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - {
          label: 'Beskrivning',
          name: description,
          widget: string,
          hint: '1-2 meningar som visas när man delar en länk till sidan.',
          default: '',
          required: false,
        }
      - {
          label: 'Dold',
          name: 'hidden',
          widget: 'boolean',
          default: false,
          hint: 'Om du vill spara utan att publicera kan du göra receptet dolt här.',
        }
      - {
          label: 'Kategori',
          name: 'category',
          widget: 'select',
          multiple: false,
          options:
            [
              'Frukost',
              'Förrätt',
              'Huvudrätt',
              'Sallad',
              'Efterrätt',
              'Bakning',
            ],
          default: ['Huvudrätt'],
        }
      - {
          label: 'Bild',
          name: 'featuredimage',
          widget: 'image',
          hint: 'Det behövs en bild, men du kan välja en standardbild i biblioteket.',
        }
      - {
          label: 'Tema för bildtext',
          name: 'featuredimagetheme',
          widget: 'select',
          options: [{ label: 'Ljus', value: 1 }, { label: 'Mörk', value: 2 }],
          hint: 'Ange om den valda bilden är mörk eller ljus i nederkant.',
        }
      - {
          label: 'Portioner/antal',
          name: 'servings',
          widget: number,
          hint: 'Ange hur många portioner receptet är tänkt för. Är det mer lämpligt att ange antal, ex. 20 bullar, ange då 20 och skriv något om detta i beskrivningen ovan.',
        }
      - {
          label: 'Delmoment med ingredienser',
          name: 'ingredients',
          widget: 'list',
          fields:
            [
              {
                label: 'Delmoment, ex. "Sås"',
                name: 'part-ingredients',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Rubrik',
                      name: 'part-ingredients-name',
                      widget: 'string',
                      required: false,
                      hint: 'Underrubrik för ett delmoment, ex. "Aioli". Visas inte om det inte finns flera delmoment.',
                    },
                    {
                      label: 'Ingredienslista, delmoment',
                      name: 'part-ingredients-list',
                      widget: 'list',
                      fields:
                        [
                          {
                            label: 'Ingrediens',
                            name: 'ingredient',
                            widget: 'object',
                            fields:
                              [
                                {
                                  label: 'Mängd',
                                  name: 'ingredient-amount',
                                  widget: 'number',
                                  valueType: 'float',
                                },
                                {
                                  label: 'Måttenhet',
                                  name: 'unit',
                                  widget: select,
                                  options:
                                    [
                                      'Styck (st)',
                                      'Deciliter (dl)',
                                      'Centiliter (cl)',
                                    ],
                                },
                                {
                                  label: 'Namn',
                                  name: 'ingredient-name',
                                  widget: 'string',
                                },
                              ],
                          },
                        ],
                    },
                  ],
              },
            ],
        }

      - { label: 'Huvudinnehåll', name: 'body', widget: 'markdown' }
      - {
          label: 'Taggar',
          label_singular: 'Tagg',
          name: 'tags',
          widget: 'list',
          required: false,
          hint: 'Taggarna är till för att kunna hitta andra recept taggade med samma sak, så ange inte få många.',
        }
