local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads
display_url: https://recept.netlify.com

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections:
  - name: 'recept'
    label: 'Recept'
    folder: 'src/pages/recept'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'recept',
        }
      - {
          label: 'Datum',
          name: 'date',
          widget: 'hidden',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          default: null,
        }
      - { label: 'URL', name: 'url', widget: 'hidden', default: '' }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - {
          label: 'Beskrivning',
          name: description,
          widget: string,
          required: false,
        }
      - {
          label: 'Redskap',
          name: tools,
          widget: string,
          hint: '',
          required: false,
        }
      - {
          label: 'Dold',
          name: 'hidden',
          widget: 'boolean',
          default: false,
          hint: 'Om du vill spara utan att publicera kan du göra receptet dolt här.',
        }
      - {
          label: 'Kategori',
          name: 'category',
          widget: 'select',
          multiple: false,
          options:
            [
              'Frukost',
              'Förrätt',
              'Huvudrätt',
              'Tillbehör',
              'Efterrätt',
              'Bakning',
            ],
          default: 'Huvudrätt',
          hint: 'Kategorin blir Huvudrätt om inget anges. Välj detta om inget annat passar in.',
        }
      - {
          label: 'Bild',
          name: 'featuredimage',
          widget: 'image',
          hint: 'Det behövs en bild, men du kan välja en standardbild i biblioteket.',
        }
      - {
          label: 'Tema för bildtext',
          name: 'featuredimagetheme',
          widget: 'select',
          default: { label: 'Ljus', value: 1 },
          options: [{ label: 'Ljus', value: 1 }, { label: 'Mörk', value: 2 }],
          hint: 'Ange om den valda bilden är mörk eller ljus i nederkant.',
        }
      - {
          label: 'Portioner/antal',
          name: 'servings',
          widget: number,
          min: 0,
          hint: 'Ange hur många portioner receptet är tänkt för. Är det mer lämpligt att ange antal, ex. 20 bullar, ange då 20 och skriv något om detta i beskrivningen ovan.',
        }
      - {
          label: 'Portioner eller annat',
          name: 'servingslabel',
          widget: 'string',
          default: 'portioner',
          hint: '"portioner" används om inget anges. Ex. "bullar", "liter"',
        }
      - {
          label: 'Grupper av ingredienser',
          name: 'ingredients',
          widget: 'list',
          fields:
            [
              {
                label: 'Delmoment, ex. "Sås"',
                name: 'partingredients',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Rubrik',
                      name: 'partingredientsname',
                      widget: 'string',
                      hint: 'Underrubrik för ett delmoment, ex. "Aioli". Visas inte om det inte finns flera delmoment.',
                    },
                    {
                      label: 'Ingredienslista, delmoment',
                      name: 'partingredientslist',
                      widget: 'list',
                      fields:
                        [
                          {
                            label: 'Ingrediens',
                            name: 'ingredient',
                            widget: 'object',
                            fields:
                              [
                                {
                                  label: 'Mängd',
                                  name: 'ingredientamount',
                                  widget: 'number',
                                  valueType: 'float',
                                  min: 0,
                                  hint: 'Ange 0 om du inte vill visa någon mängd, ex. "salt"',
                                },
                                {
                                  label: 'Måttenhet',
                                  name: 'unit',
                                  widget: select,
                                  options:
                                    [
                                      { label: 'Styck (st)', value: 'st' },
                                      { label: 'Liter (l)', value: 'l' },
                                      { label: 'Deciliter (dl)', value: 'dl' },
                                      { label: 'Centiliter (cl)', value: 'cl' },
                                      { label: 'Milliliter (ml)', value: 'ml' },
                                      { label: 'Matsked (msk)', value: 'msk' },
                                      { label: 'Tesked (tsk)', value: 'tsk' },
                                      { label: 'Gram (g)', value: 'g' },
                                      { label: 'Hekto (hg)', value: 'hg' },
                                      { label: 'Kilo (kg)', value: 'kg' },
                                    ],
                                },
                                {
                                  label: 'Namn',
                                  name: 'ingredientname',
                                  widget: 'string',
                                },
                              ],
                          },
                        ],
                    },
                  ],
              },
            ],
        }
      - {
          label: 'Grupper av instruktioner',
          name: 'instructions',
          widget: 'list',
          fields:
            [
              {
                label: 'Grupp av instruktioner',
                name: 'partinstructions',
                widget: 'object',
                fields:
                  [
                    {
                      label: 'Rubrik',
                      name: partinstructionsname,
                      widget: string,
                      hint: 'Ex. "Sås". Kan lämnas tom om det bara finns ett moment.',
                    },
                    {
                      label: 'Instruktioner för delmoment',
                      name: 'partinstructionslist',
                      widget: 'list',
                      fields:
                        [
                          {
                            label: 'Instruktion',
                            name: instruction,
                            widget: 'string',
                          },
                        ],
                    },
                  ],
              },
            ],
        }
      - {
          label: 'Avslutande ord',
          name: 'body',
          widget: 'markdown',
          buttons: ['bold', 'italic', 'link'],
          required: false,
        }
      - {
          label: 'Väntetid',
          name: 'timepassive',
          widget: 'object',
          fields:
            [
              {
                label: 'Dagar',
                name: 'dayspassive',
                widget: number,
                default: 0,
                min: 0,
              },
              {
                label: 'Timmar',
                name: 'hourspassive',
                widget: number,
                default: 0,
                min: 0,
              },
              {
                label: 'Minuter',
                name: 'minutespassive',
                widget: number,
                default: 0,
                min: 0,
              },
            ],
        }
      - {
          label: 'Aktiv tillagningstid',
          name: 'timeactive',
          widget: 'object',
          fields:
            [
              {
                label: 'Timmar',
                name: 'hoursactive',
                widget: number,
                default: 0,
                min: 0,
              },
              {
                label: 'Minuter',
                name: 'minutesactive',
                widget: number,
                default: 0,
                min: 0,
              },
            ],
        }
      - {
          label: 'Taggar',
          label_singular: 'Tagg',
          name: 'tags',
          widget: 'list',
          required: false,
          hint: 'Taggarna är till för att kunna hitta andra recept taggade med samma sak, så ange inte få många.',
        }
