name: Recipe tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: bahmutov/npm-install@HEAD

      - name: Run ESLint
        run: |
          npm run lint
      - name: Unit tests
        run: |
          npm run test:unit
      - name: Integration tests
        run: |
          npm run test:cypress:ci
